site_name: Black Desert 2026 — гайд для новичков
site_description: Пошаговый маршрут для плавного старта в Black Desert

theme:
  name: material
  custom_dir: overrides
  language: ru
  features:
    - navigation.footer
    - navigation.top
    - search.suggest

plugins:
  - search:
      lang: ru

hooks:
  - hooks/guide.py

markdown_extensions:
  - attr_list
  - toc:
      toc_depth: 2-3
      permalink: true
